[project]
name = "ErisPulse-BiliParser"
version = "1.0.3"
description = "B站视频解析模块，自动解析视频链接并展示详细信息、热门评论与弹幕"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [ { name = "wsu2059", email = "wsu2059@qq.com" } ]

dependencies = [
    "bilibili-api-python>=16.0.0",
]

[project.entry-points."erispulse.module"]
"BiliParser" = "BiliParser:Main"
